title: Notisbuilds
description: Building cool stuff in public
author: Notisbuilds
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: /posts/:title/

# Social links
twitter_username: notisbuilds
github_username: notkatsa

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
